# Generated by Django 3.2.2 on 2021-05-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customernickname',
            field=models.CharField(db_column='customerNickName', max_length=50, null=True),
        ),
    ]
